apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-r3hs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-r3hs
    app.kubernetes.io/part-of: tkrw-pr712-0075-0065-app
  name: devfile-sample-r3hs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-r3hs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-r3hs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-r3hs@sha256:a9a5a2d189be38d1b7407b09fc4f12f8fa8a7368db4f29bce7259003e07c1bdc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
